# Generated by Django 3.1.2 on 2020-10-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('birth_date', models.DateTimeField(verbose_name='birth date ')),
                ('entry_date', models.DateTimeField(verbose_name='entry date ')),
                ('photo', models.CharField(max_length=20)),
                ('idBirthCertificate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TelTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telNrTeacher', models.CharField(max_length=30)),
                ('telTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
