# Generated by Django 3.1.2 on 2020-10-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='tel',
            new_name='dep',
        ),
    ]
